[package]
name = "widle"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31.12"
wayland-protocols = { version = "0.32.10", features = ["staging", "client"] }
zbus = { version = "5.13.1", features = ["blocking"] }

